/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinscript

// trivial useless main -- doesnt work well with gradle
// ./gradlew run --args="println(1)"
fun main(args: Array<String>) {
    require(args.size > 0)
    val body = args[0]
    val params = args.drop(1).zipWithNext().toMap()
    evaluateScript( body , params )
}
